"""add SR_Tickets

Revision ID: 0859d42db548
Revises: 147eb0ea8aa1
Create Date: 2026-02-06 11:00:19.807926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0859d42db548'
down_revision = '147eb0ea8aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IDC_Site', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.drop_column('IDC_Site')

    # ### end Alembic commands ###
