"""Added Phone column to CTM_People

Revision ID: 0dba06d6ac69
Revises: 3149e05b313b
Create Date: 2026-02-05 11:12:47.101820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dba06d6ac69'
down_revision = '3149e05b313b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Service_Number', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Service_Status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('IDC', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Rack_Location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Client_Sensitivity', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Report_YN', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Customer_Folder', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Customer_Folder_Detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Service_URL__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Business_Type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Business_Detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Backup_Service', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Backup_Type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Backup_Period', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Backup_Path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Vaccine__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ShellMonitor__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Other_Info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.drop_column('Other_Info')
        batch_op.drop_column('ShellMonitor__c')
        batch_op.drop_column('Vaccine__c')
        batch_op.drop_column('Backup_Path')
        batch_op.drop_column('Backup_Period')
        batch_op.drop_column('Backup_Type')
        batch_op.drop_column('Backup_Service')
        batch_op.drop_column('Business_Detail')
        batch_op.drop_column('Business_Type')
        batch_op.drop_column('Service_URL__c')
        batch_op.drop_column('Customer_Folder_Detail')
        batch_op.drop_column('Customer_Folder')
        batch_op.drop_column('Report_YN')
        batch_op.drop_column('Client_Sensitivity')
        batch_op.drop_column('Rack_Location')
        batch_op.drop_column('IDC')
        batch_op.drop_column('Service_Status')
        batch_op.drop_column('Service_Number')

    # ### end Alembic commands ###
