"""add SR_Tickets

Revision ID: 147eb0ea8aa1
Revises: 79add524636b
Create Date: 2026-02-06 10:59:41.945152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147eb0ea8aa1'
down_revision = '79add524636b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Region', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.drop_column('Region')

    # ### end Alembic commands ###
