"""Added Phone column to CTM_People

Revision ID: 3149e05b313b
Revises: ca2048d6fbce
Create Date: 2026-02-05 10:55:44.980757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3149e05b313b'
down_revision = 'ca2048d6fbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CTM_ID', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('sp_secure_dashboard_link__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sp_issue_dashboard_link__c', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['Person_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sp_issue_dashboard_link__c')
        batch_op.drop_column('sp_secure_dashboard_link__c')
        batch_op.drop_column('CTM_ID')

    # ### end Alembic commands ###
