"""add SR_Tickets

Revision ID: 614ab2f7dff6
Revises: b683729ab710
Create Date: 2026-02-04 17:03:05.351761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ab2f7dff6'
down_revision = 'b683729ab710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SR_Tickets',
    sa.Column('SR_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Company', sa.Text(), nullable=False),
    sa.Column('Location', sa.Text(), nullable=False),
    sa.Column('Request_Date', sa.Date(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Handler', sa.Text(), nullable=False),
    sa.Column('Created_By', sa.Text(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Text(), nullable=True),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SR_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SR_Tickets')
    # ### end Alembic commands ###
