"""add SR_Tickets

Revision ID: 79add524636b
Revises: efcfa747de53
Create Date: 2026-02-06 10:58:41.771111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79add524636b'
down_revision = 'efcfa747de53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IP_Address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.drop_column('IP_Address')

    # ### end Alembic commands ###
