"""Fix FK string

Revision ID: b683729ab710
Revises: 
Create Date: 2026-02-04 16:19:25.644829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b683729ab710'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CTM_People',
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Company', sa.Text(), nullable=True),
    sa.Column('Last_Name', sa.Text(), nullable=True),
    sa.Column('Submit_Date', sa.DateTime(), nullable=True),
    sa.Column('Report_YN', sa.Text(), nullable=True),
    sa.Column('Client_Sensitivity', sa.Text(), nullable=True),
    sa.Column('Service_Type', sa.Text(), nullable=True),
    sa.Column('Rack_Location', sa.Text(), nullable=True),
    sa.Column('IDC', sa.Text(), nullable=True),
    sa.Column('Backup_Path', sa.Text(), nullable=True),
    sa.Column('Backup_Service', sa.Text(), nullable=True),
    sa.Column('Backup_Type', sa.Text(), nullable=True),
    sa.Column('Service_URL__c', sa.Text(), nullable=True),
    sa.Column('Vaccine__c', sa.Text(), nullable=True),
    sa.Column('ShellMonitor__c', sa.Text(), nullable=True),
    sa.Column('Backup_Volume__c', sa.Text(), nullable=True),
    sa.Column('chServiceNumber', sa.Text(), nullable=True),
    sa.Column('Customer_Folder', sa.Text(), nullable=True),
    sa.Column('Opening_Date', sa.Date(), nullable=True),
    sa.Column('Termination_Date', sa.Date(), nullable=True),
    sa.Column('Business_Type', sa.Text(), nullable=True),
    sa.Column('Business_Detail', sa.Text(), nullable=True),
    sa.Column('Intrusion_Detection_Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Person_ID')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('AST_ComputerSystem',
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('AssetLifecycleStatus', sa.Text(), nullable=True),
    sa.Column('Short_Description', sa.Text(), nullable=True),
    sa.Column('C_backup', sa.Text(), nullable=True),
    sa.Column('Operating_Mode__c', sa.Text(), nullable=True),
    sa.Column('C_note', sa.Text(), nullable=True),
    sa.Column('C_cycle', sa.Text(), nullable=True),
    sa.Column('Supported_By', sa.Text(), nullable=True),
    sa.Column('Disposal_Date', sa.Date(), nullable=True),
    sa.Column('Available_Date', sa.Date(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('Purchase_Date', sa.Date(), nullable=True),
    sa.Column('Manufacturer', sa.Text(), nullable=True),
    sa.Column('Version_Number', sa.Text(), nullable=True),
    sa.Column('Model_Number', sa.Text(), nullable=True),
    sa.Column('Manufacturer_Name', sa.Text(), nullable=True),
    sa.Column('Supplier', sa.Text(), nullable=True),
    sa.Column('Owner_Name', sa.Text(), nullable=True),
    sa.Column('Region', sa.Text(), nullable=True),
    sa.Column('Category', sa.Text(), nullable=True),
    sa.Column('Serial_Number', sa.Text(), nullable=True),
    sa.Column('Item', sa.Text(), nullable=True),
    sa.Column('Type', sa.Text(), nullable=True),
    sa.Column('IP_Address', sa.Text(), nullable=True),
    sa.Column('LastScanDate', sa.DateTime(), nullable=True),
    sa.Column('InstallationDate', sa.Date(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Name')
    )
    op.create_table('Access_Details',
    sa.Column('Access_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Login_ID', sa.Text(), nullable=True),
    sa.Column('SecurityPortal_URL', sa.Text(), nullable=True),
    sa.Column('Dashboard_URL', sa.Text(), nullable=True),
    sa.Column('IssueDashboard_URL', sa.Text(), nullable=True),
    sa.Column('Token', sa.Text(), nullable=True),
    sa.Column('License_Default', sa.Text(), nullable=True),
    sa.Column('License_Type', sa.Text(), nullable=True),
    sa.Column('Permission_Group', sa.Text(), nullable=True),
    sa.Column('Access_Restriction', sa.Text(), nullable=True),
    sa.Column('Unlimited_Access_YN', sa.Text(), nullable=True),
    sa.Column('Password_Vault_Ref', sa.Text(), nullable=True),
    sa.Column('Password_Changed_Date', sa.Date(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=False),
    sa.Column('Create_Date', sa.DateTime(), nullable=False),
    sa.Column('Updater', sa.Text(), nullable=True),
    sa.Column('Update_Date', sa.DateTime(), nullable=True),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Access_ID')
    )
    op.create_table('Contacts',
    sa.Column('Contact_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Contact_Type', sa.Text(), nullable=True),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Phone', sa.Text(), nullable=True),
    sa.Column('Mobile', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('Status', sa.Text(), nullable=True),
    sa.Column('Intrusion_Receive_YN', sa.Text(), nullable=True),
    sa.Column('Report_Receive_YN', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=False),
    sa.Column('Create_Date', sa.DateTime(), nullable=False),
    sa.Column('Updater', sa.Text(), nullable=True),
    sa.Column('Update_Date', sa.DateTime(), nullable=True),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Contact_ID')
    )
    op.create_table('Contracts',
    sa.Column('Contract_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Contract_Name', sa.Text(), nullable=True),
    sa.Column('Contract_Amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('Currency', sa.Text(), nullable=True),
    sa.Column('Contract_Start_Date', sa.Date(), nullable=True),
    sa.Column('Contract_End_Date', sa.Date(), nullable=True),
    sa.Column('Contract_Notes', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=False),
    sa.Column('Create_Date', sa.DateTime(), nullable=False),
    sa.Column('Updater', sa.Text(), nullable=True),
    sa.Column('Update_Date', sa.DateTime(), nullable=True),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Contract_ID')
    )
    op.create_table('Customer_Notes',
    sa.Column('Note_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Severity', sa.Text(), nullable=False),
    sa.Column('Tags', sa.Text(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Created_By', sa.Text(), nullable=False),
    sa.Column('Created_At', sa.DateTime(), nullable=False),
    sa.Column('Updated_By', sa.Text(), nullable=True),
    sa.Column('Updated_At', sa.DateTime(), nullable=True),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_By', sa.Text(), nullable=True),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Note_ID')
    )
    op.create_table('Servers',
    sa.Column('People ID', sa.Text(), nullable=False),
    sa.Column('chServerName', sa.Text(), nullable=False),
    sa.Column('chServerInfo', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=True),
    sa.Column('Create Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['People ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('People ID', 'chServerName')
    )
    op.create_table('Work_Info',
    sa.Column('Work_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('Work_Date', sa.DateTime(), nullable=True),
    sa.Column('Work_Type', sa.Text(), nullable=True),
    sa.Column('Work_Summary', sa.Text(), nullable=True),
    sa.Column('Work_Detail', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=False),
    sa.Column('Create_Date', sa.DateTime(), nullable=False),
    sa.Column('Updater', sa.Text(), nullable=True),
    sa.Column('Update_Date', sa.DateTime(), nullable=True),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Work_ID')
    )
    op.create_table('Note_Attachments',
    sa.Column('Attachment_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Note_ID', sa.BigInteger(), nullable=False),
    sa.Column('Original_Filename', sa.Text(), nullable=False),
    sa.Column('Stored_Filename', sa.Text(), nullable=False),
    sa.Column('Content_Type', sa.Text(), nullable=True),
    sa.Column('Size_Bytes', sa.BigInteger(), nullable=False),
    sa.Column('Uploaded_By', sa.Text(), nullable=False),
    sa.Column('Uploaded_At', sa.DateTime(), nullable=False),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Note_ID'], ['Customer_Notes.Note_ID'], ),
    sa.PrimaryKeyConstraint('Attachment_ID')
    )
    op.create_table('Work_Attachments',
    sa.Column('Attachment_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Work_ID', sa.BigInteger(), nullable=False),
    sa.Column('Original_Filename', sa.Text(), nullable=False),
    sa.Column('Stored_Filename', sa.Text(), nullable=False),
    sa.Column('Size_Bytes', sa.BigInteger(), nullable=False),
    sa.Column('Content_Type', sa.Text(), nullable=True),
    sa.Column('Uploaded_By', sa.Text(), nullable=False),
    sa.Column('Uploaded_At', sa.DateTime(), nullable=False),
    sa.Column('Deleted_YN', sa.Text(), nullable=False),
    sa.Column('Deleted_At', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Work_ID'], ['Work_Info.Work_ID'], ),
    sa.PrimaryKeyConstraint('Attachment_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Work_Attachments')
    op.drop_table('Note_Attachments')
    op.drop_table('Work_Info')
    op.drop_table('Servers')
    op.drop_table('Customer_Notes')
    op.drop_table('Contracts')
    op.drop_table('Contacts')
    op.drop_table('Access_Details')
    op.drop_table('AST_ComputerSystem')
    op.drop_table('users')
    op.drop_table('CTM_People')
    # ### end Alembic commands ###
