"""Added Phone column to CTM_People

Revision ID: b9924b1da20a
Revises: 0dba06d6ac69
Create Date: 2026-02-05 11:18:20.991492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9924b1da20a'
down_revision = '0dba06d6ac69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.drop_column('sp_issue_dashboard_link__c')
        batch_op.drop_column('Customer_SR__c')
        batch_op.drop_column('Service_Contract_Amount_KRW__c')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Service_Contract_Amount_KRW__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Customer_SR__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sp_issue_dashboard_link__c', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
