"""add SR_Tickets

Revision ID: c638af7c40ce
Revises: 614ab2f7dff6
Create Date: 2026-02-04 17:58:33.060130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c638af7c40ce'
down_revision = '614ab2f7dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SR_Tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Severity', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Requester', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Handled_Date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('Result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Remark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SR_Tickets', schema=None) as batch_op:
        batch_op.drop_column('Remark')
        batch_op.drop_column('Result')
        batch_op.drop_column('Handled_Date')
        batch_op.drop_column('Requester')
        batch_op.drop_column('Severity')
        batch_op.drop_column('Category')

    # ### end Alembic commands ###
