"""Added Phone column to CTM_People

Revision ID: ca2048d6fbce
Revises: c638af7c40ce
Create Date: 2026-02-05 10:37:37.365660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca2048d6fbce'
down_revision = 'c638af7c40ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AST_Computer_System',
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('AssetLifecycleStatus', sa.Integer(), nullable=True),
    sa.Column('Short_Description', sa.Text(), nullable=True),
    sa.Column('C_backup', sa.Integer(), nullable=True),
    sa.Column('Operating_Mode__c', sa.Integer(), nullable=True),
    sa.Column('C_note', sa.Text(), nullable=True),
    sa.Column('C_cycle', sa.Integer(), nullable=True),
    sa.Column('Supported', sa.Integer(), nullable=True),
    sa.Column('Disposal_Date', sa.Date(), nullable=True),
    sa.Column('Available_Date', sa.Date(), nullable=True),
    sa.Column('Receive_Date', sa.Date(), nullable=True),
    sa.Column('ReturnDate', sa.Date(), nullable=True),
    sa.Column('PurchaseDate', sa.Date(), nullable=True),
    sa.Column('Manufacturer', sa.Text(), nullable=True),
    sa.Column('Version_Number', sa.Text(), nullable=True),
    sa.Column('Model_Number', sa.Text(), nullable=True),
    sa.Column('Manufacturer_Name', sa.Text(), nullable=True),
    sa.Column('Supplier_Name', sa.Text(), nullable=True),
    sa.Column('Owner_Name', sa.Text(), nullable=True),
    sa.Column('Region', sa.Text(), nullable=True),
    sa.Column('Category', sa.Text(), nullable=True),
    sa.Column('Serial_Number', sa.Text(), nullable=True),
    sa.Column('Item', sa.Text(), nullable=True),
    sa.Column('Type', sa.Text(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('LastScanDate', sa.DateTime(), nullable=True),
    sa.Column('InstallationDate', sa.Date(), nullable=True),
    sa.Column('Room', sa.Text(), nullable=True),
    sa.Column('Building', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Name')
    )
    op.create_table('Server_Info',
    sa.Column('Server_ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Person_ID', sa.Text(), nullable=False),
    sa.Column('chServerName', sa.Text(), nullable=True),
    sa.Column('chServerInfo', sa.Text(), nullable=True),
    sa.Column('Submitter', sa.Text(), nullable=True),
    sa.Column('Create_Date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], ),
    sa.PrimaryKeyConstraint('Server_ID')
    )
    op.drop_table('AST_ComputerSystem')
    op.drop_table('Servers')
    with op.batch_alter_table('Access_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Password_Hash', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Access_Restrictions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sp_secure_dashboard_link__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sp_issue_dashboard_link__c', sa.Text(), nullable=True))
        batch_op.drop_column('Deleted_YN')
        batch_op.drop_column('SecurityPortal_URL')
        batch_op.drop_column('Password_Changed_Date')
        batch_op.drop_column('Create_Date')
        batch_op.drop_column('License_Default')
        batch_op.drop_column('Submitter')
        batch_op.drop_column('Permission_Group')
        batch_op.drop_column('Access_Restriction')
        batch_op.drop_column('Unlimited_Access_YN')
        batch_op.drop_column('Update_Date')
        batch_op.drop_column('Dashboard_URL')
        batch_op.drop_column('Updater')
        batch_op.drop_column('Deleted_At')
        batch_op.drop_column('Password_Vault_Ref')
        batch_op.drop_column('IssueDashboard_URL')
        batch_op.drop_column('Description')

    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Customer_Name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Client_Type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Open_Date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('Terminate_Date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('chHistory', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chEtc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Sales_Manager', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Customer_SR__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contract_memo__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Service_Contract_Amount__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Service_Contract_Amount_KRW__c', sa.Text(), nullable=True))
        batch_op.drop_column('chServiceNumber')
        batch_op.drop_column('Opening_Date')
        batch_op.drop_column('Client_Sensitivity')
        batch_op.drop_column('Rack_Location')
        batch_op.drop_column('Backup_Service')
        batch_op.drop_column('Submit_Date')
        batch_op.drop_column('Business_Type')
        batch_op.drop_column('Termination_Date')
        batch_op.drop_column('Intrusion_Detection_Notes')
        batch_op.drop_column('ShellMonitor__c')
        batch_op.drop_column('Business_Detail')
        batch_op.drop_column('Service_URL__c')
        batch_op.drop_column('Backup_Volume__c')
        batch_op.drop_column('Backup_Path')
        batch_op.drop_column('IDC')
        batch_op.drop_column('Customer_Folder')
        batch_op.drop_column('Vaccine__c')
        batch_op.drop_column('Backup_Type')
        batch_op.drop_column('Report_YN')

    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role_Type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('SMS_Receive_YN', sa.Text(), nullable=True))
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('Deleted_YN')
        batch_op.drop_column('Submitter')
        batch_op.drop_column('Contact_Type')
        batch_op.drop_column('Mobile')
        batch_op.drop_column('Update_Date')
        batch_op.drop_column('Updater')
        batch_op.drop_column('Deleted_At')
        batch_op.drop_column('Intrusion_Receive_YN')
        batch_op.drop_column('Create_Date')

    with op.batch_alter_table('Work_Attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('File_Name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('File_Path', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('File_Size', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('Upload_Date', sa.DateTime(), nullable=False))
        batch_op.drop_column('Deleted_YN')
        batch_op.drop_column('Stored_Filename')
        batch_op.drop_column('Size_Bytes')
        batch_op.drop_column('Uploaded_By')
        batch_op.drop_column('Content_Type')
        batch_op.drop_column('Uploaded_At')
        batch_op.drop_column('Deleted_At')
        batch_op.drop_column('Original_Filename')

    with op.batch_alter_table('Work_Info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Attachment_YN', sa.Text(), nullable=False))
        batch_op.alter_column('Work_Date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('Work_Detail')
        batch_op.drop_column('Deleted_YN')
        batch_op.drop_column('Work_Summary')
        batch_op.drop_column('Update_Date')
        batch_op.drop_column('Updater')
        batch_op.drop_column('Deleted_At')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Work_Info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Deleted_At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Updater', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Update_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Work_Summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deleted_YN', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Work_Detail', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('Work_Date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('Attachment_YN')
        batch_op.drop_column('Description')
        batch_op.drop_column('Summary')

    with op.batch_alter_table('Work_Attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Original_Filename', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Deleted_At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Uploaded_At', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Content_Type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Uploaded_By', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Size_Bytes', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Stored_Filename', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Deleted_YN', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('Upload_Date')
        batch_op.drop_column('File_Size')
        batch_op.drop_column('File_Path')
        batch_op.drop_column('File_Name')

    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Create_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Intrusion_Receive_YN', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deleted_At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Updater', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Update_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Mobile', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Contact_Type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Submitter', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Deleted_YN', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('SMS_Receive_YN')
        batch_op.drop_column('Role_Type')

    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Report_YN', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Backup_Type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Vaccine__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Customer_Folder', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IDC', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Backup_Path', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Backup_Volume__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Service_URL__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Business_Detail', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ShellMonitor__c', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Intrusion_Detection_Notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Termination_Date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Business_Type', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Submit_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Backup_Service', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Rack_Location', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Client_Sensitivity', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Opening_Date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chServiceNumber', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('Service_Contract_Amount_KRW__c')
        batch_op.drop_column('Service_Contract_Amount__c')
        batch_op.drop_column('contract_memo__c')
        batch_op.drop_column('Customer_SR__c')
        batch_op.drop_column('Sales_Manager')
        batch_op.drop_column('chEtc')
        batch_op.drop_column('chHistory')
        batch_op.drop_column('Terminate_Date')
        batch_op.drop_column('Open_Date')
        batch_op.drop_column('Client_Type')
        batch_op.drop_column('Customer_Name')

    with op.batch_alter_table('Access_Details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('IssueDashboard_URL', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Password_Vault_Ref', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deleted_At', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Updater', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Dashboard_URL', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Update_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Unlimited_Access_YN', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Access_Restriction', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Permission_Group', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Submitter', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('License_Default', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Create_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Password_Changed_Date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('SecurityPortal_URL', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Deleted_YN', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('sp_issue_dashboard_link__c')
        batch_op.drop_column('sp_secure_dashboard_link__c')
        batch_op.drop_column('Access_Restrictions')
        batch_op.drop_column('Password_Hash')

    op.create_table('Servers',
    sa.Column('People ID', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chServerName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chServerInfo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Submitter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Create Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['People ID'], ['CTM_People.Person_ID'], name=op.f('Servers_People ID_fkey')),
    sa.PrimaryKeyConstraint('People ID', 'chServerName', name=op.f('Servers_pkey'))
    )
    op.create_table('AST_ComputerSystem',
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('AssetLifecycleStatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Short_Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('C_backup', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Operating_Mode__c', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('C_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('C_cycle', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Supported_By', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Disposal_Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Available_Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ReturnDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Purchase_Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Manufacturer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Version_Number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Model_Number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Manufacturer_Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Supplier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Owner_Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Serial_Number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Item', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('IP_Address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('LastScanDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('InstallationDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Person_ID', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Person_ID'], ['CTM_People.Person_ID'], name=op.f('AST_ComputerSystem_Person_ID_fkey')),
    sa.PrimaryKeyConstraint('Name', name=op.f('AST_ComputerSystem_pkey'))
    )
    op.drop_table('Server_Info')
    op.drop_table('AST_Computer_System')
    # ### end Alembic commands ###
