"""add SR_Tickets

Revision ID: d05747165b3e
Revises: 0859d42db548
Create Date: 2026-02-06 11:01:27.762452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05747165b3e'
down_revision = '0859d42db548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Maintenance_Company', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Operation_Company', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Operation_Mode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Product_Name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Supplier', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Owner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('License_Expiry_Date', sa.Date(), nullable=True))
        batch_op.drop_column('유지보수업체__c')
        batch_op.drop_column('운영모드__c')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('운영모드__c', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('유지보수업체__c', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('License_Expiry_Date')
        batch_op.drop_column('Owner')
        batch_op.drop_column('Supplier')
        batch_op.drop_column('Product_Name')
        batch_op.drop_column('Operation_Mode')
        batch_op.drop_column('Operation_Company')
        batch_op.drop_column('Maintenance_Company')

    # ### end Alembic commands ###
