"""Added Phone column to CTM_People

Revision ID: de152eccf991
Revises: b9924b1da20a
Create Date: 2026-02-05 13:06:51.445220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de152eccf991'
down_revision = 'b9924b1da20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.drop_column('sp_secure_dashboard_link__c')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CTM_People', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sp_secure_dashboard_link__c', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
