"""add SR_Tickets

Revision ID: efcfa747de53
Revises: de152eccf991
Create Date: 2026-02-05 16:32:54.820614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efcfa747de53'
down_revision = 'de152eccf991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Company', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Owner_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Service_URL__c', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('유지보수업체__c', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('운영모드__c', sa.Integer(), nullable=True))
        batch_op.alter_column('Asset_ID',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('LastScanDate',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['Name'])
        batch_op.drop_column('Room')
        batch_op.drop_column('Supplier_Name')
        batch_op.drop_column('Owner_Name')
        batch_op.drop_column('Operating_Mode__c')
        batch_op.drop_column('Region')
        batch_op.drop_column('Manufacturer')
        batch_op.drop_column('Building')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AST_Computer_System', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Building', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Manufacturer', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Region', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Operating_Mode__c', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Owner_Name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Supplier_Name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Room', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('LastScanDate',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('Asset_ID',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('운영모드__c')
        batch_op.drop_column('유지보수업체__c')
        batch_op.drop_column('Service_URL__c')
        batch_op.drop_column('Owner_name')
        batch_op.drop_column('Company')

    # ### end Alembic commands ###
